name: blue
description: "Bluetooth & Wi-Fi App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5<4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility Package
  intl: ^0.20.1
  location: ^7.0.1
  url_launcher: ^6.2.6
  connectivity_plus: ^6.1.0
  permission_handler: ^11.3.1
  smooth_page_indicator: ^1.1.0

  fl_chart: ^0.70.2
  file_picker: ^10.3.3
  csv: ^6.0.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7

  # Flutter
  flutter_lints: ^5.0.0
  flutter_spinkit: ^5.2.1
  flutter_native_splash: ^2.4.0
  flutter_blue_plus: ^1.31.15
  path_provider: ^2.1.5

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

#<----------------- PACKAGE END ----------------->

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/