# name: blue
# description: "A Bluetooth & WIFI App"
# publish_to: 'none'
# version: 1.0.0+1

# environment:
#   sdk: '>=3.1.5 < 4.5.0'

# dependencies:
#   flutter:
#     sdk: flutter

#   # Utility Package
#   intl: ^0.20.1
#   url_launcher: ^6.2.6
#   flutter_lints: ^5.0.0
#   connectivity_plus: ^6.1.0
#   smooth_page_indicator: ^1.1.0
#   flutter_native_splash: ^2.4.0

#   # Bluetooth Package
#   flutter_bluetooth_serial: ^0.4.0
#   permission_handler: ^11.3.1

#   #Wifi Package
#   wifi_iot: ^0.3.19+1
#   # Icons
#   iconsax: ^0.0.8
#   cupertino_icons: ^1.0.8

#   # State Management
#   get: ^4.6.6
#   get_storage: ^2.1.1
#   geolocator: ^13.0.2

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

# #<----------------- PACKAGE END ----------------->

# flutter:
#   uses-material-design: true

#   # Assets
#   assets:
#     - assets/images/


name: blue
description: "Bluetooth & Wi-Fi App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5<4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility Package
  intl: ^0.20.1
  location: ^7.0.1
  wifi_iot: ^0.3.19+1
  url_launcher: ^6.2.6
  flutter_lints: ^5.0.0
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.1.0
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.4.0

  # Bluetooth Package
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

#<----------------- PACKAGE END ----------------->

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/